### ISSUE TITLE
Should look for PKG-INFO in {package}.egg-info

### ISSUE THREAD

**Issue by yarikoptic** [jwodder/versioningit#29]
satellite to #28 

pypi distributed source .tar.gz carries `{package}.egg-info` with PKG-INFO (so `PKG-INFO` is not in the root of the project where setup.py is).  versioningit seems to look for it in the root of the project

<details>
<summary>detailed run of python3 setup.py --fullname on heudiconv</summary> 

```shell
root@smaug:/build/heudiconv-0.11.1# grep Vers heudiconv.egg-info/PKG-INFO
Metadata-Version: 2.1
Version: 0.11.1

root@smaug:/build/heudiconv-0.11.1# python3 setup.py --fullname
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/versioningit/git.py", line 145, in ensure_is_repo
    self.read(
  File "/usr/local/lib/python3.10/dist-packages/versioningit/git.py", line 177, in read
    return readcmd("git", *args, cwd=str(self.path), **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/versioningit/util.py", line 56, in readcmd
    s = runcmd(*args, stdout=subprocess.PIPE, universal_newlines=True, **kwargs).stdout
  File "/usr/local/lib/python3.10/dist-packages/versioningit/util.py", line 51, in runcmd
    return subprocess.run(arglist, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'rev-parse', '--is-inside-work-tree']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/versioningit/core.py", line 308, in get_version
    version = vgit.get_version()
  File "/usr/local/lib/python3.10/dist-packages/versioningit/core.py", line 149, in get_version
    description = self.do_vcs()
  File "/usr/local/lib/python3.10/dist-packages/versioningit/core.py", line 188, in do_vcs
    description = self.vcs(project_dir=self.project_dir)
  File "/usr/local/lib/python3.10/dist-packages/versioningit/methods.py", line 154, in __call__
    return self.method(params=self.params, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/versioningit/git.py", line 226, in describe_git
    repo.ensure_is_repo()
  File "/usr/local/lib/python3.10/dist-packages/versioningit/git.py", line 155, in ensure_is_repo
    raise NotVCSError(f"{self.path} is not in a Git repository")
versioningit.errors.NotVCSError: /build/heudiconv-0.11.1 is not in a Git repository

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/versioningit/core.py", line 370, in get_version_from_pkg_info
    Path(project_dir, "PKG-INFO").read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1132, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/build/heudiconv-0.11.1/PKG-INFO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/versioningit/hook.py", line 18, in setuptools_finalizer
    version = get_version(PROJECT_ROOT, write=True, fallback=True)
  File "/usr/local/lib/python3.10/dist-packages/versioningit/core.py", line 313, in get_version
    version = get_version_from_pkg_info(project_dir)
  File "/usr/local/lib/python3.10/dist-packages/versioningit/core.py", line 373, in get_version_from_pkg_info
    raise NotSdistError(f"{project_dir} does not contain a PKG-INFO file")
versioningit.errors.NotSdistError: /build/heudiconv-0.11.1 does not contain a PKG-INFO file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/heudiconv-0.11.1/setup.py", line 66, in <module>
    main()
  File "/build/heudiconv-0.11.1/setup.py", line 40, in main
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 459, in __init__
    _Distribution.__init__(
  File "/usr/lib/python3.10/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 837, in finalize_options
    ep(self)
  File "/usr/local/lib/python3.10/dist-packages/versioningit/hook.py", line 23, in setuptools_finalizer
    raise RuntimeError(
RuntimeError:
versioningit could not find a version for the project in /build/heudiconv-0.11.1!

You may be installing from a shallow clone, in which case you need to unshallow it first.

Alternatively, you may be installing from a Git archive, which is not supported by default.  Install from a git+https://... URL instead.



```
</details>

dirty workaround symlinking that file shows that it works then o pick up version from it

```
root@smaug:/build/heudiconv-0.11.1# ln -s heudiconv.egg-info/PKG-INFO .
root@smaug:/build/heudiconv-0.11.1# python3 setup.py --fullname
heudiconv-0.11.1
```

**Comment by jwodder** [comment]
For the record, if I download & unpack [heudiconv-0.11.1.tar.gz](https://files.pythonhosted.org/packages/36/4d/f3ce51dba7bac3d000eda30a2c1afb9f746271d10ec019803141930a006a/heudiconv-0.11.1.tar.gz), `cd` into it, create a virtualenv with `versioningit` installed, and run `python setup.py --fullname`, I get "`heudiconv-0.11.1`" as the output, no errors.
