### ISSUE TITLE
Failure when a repository doesn't have tags

### ISSUE THREAD

**Issue by Changaco** [jwodder/versioningit#98]
`versioningit` currently can't be used on any new project that hasn't had a release yet:

```python-traceback
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/…/python3.12/site-packages/hatchling/__main__.py", line 6, in <module>
    sys.exit(hatchling())
             ^^^^^^^^^^^
  File "/…/python3.12/site-packages/hatchling/cli/__init__.py", line 26, in hatchling
    command(**kwargs)
  File "/…/python3.12/site-packages/hatchling/cli/build/__init__.py", line 82, in build_impl
    for artifact in builder.build(
                    ^^^^^^^^^^^^^^
  File "/…/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 90, in build
    self.metadata.validate_fields()
  File "/…/python3.12/site-packages/hatchling/metadata/core.py", line 265, in validate_fields
    _ = self.version
        ^^^^^^^^^^^^
  File "/…/python3.12/site-packages/hatchling/metadata/core.py", line 149, in version
    self._version = self._get_version()
                    ^^^^^^^^^^^^^^^^^^^
  File "/…/python3.12/site-packages/hatchling/metadata/core.py", line 248, in _get_version
    version = self.hatch.version.cached
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/…/python3.12/site-packages/hatchling/metadata/core.py", line 1466, in cached
    raise type(e)(message) from None
RuntimeError: Error getting the version from source `versioningit`: NoTagError: `git describe --long --dirty --always --tags` could not find a tag

versioningit could not find a version for the project in /path!

You may be installing from a shallow clone, in which case you need to unshallow it first.

Alternatively, you may be installing from a Git archive, which is not supported by default.  Install from a git+https://... URL instead.
```

In the same situation, `setuptools_scm` generates a default version number that looks like `0.1.dev{distance}+{vcs}{rev}`.

(Feel free to close this issue as “won't fix”.)

**Comment by jwodder** [comment]
This is intentional, and it's mentioned as the intended behavior in the README (and the main page of the RTD docs) in the last paragraph of ["Installation & Setup"](https://github.com/jwodder/versioningit?tab=readme-ov-file#installation--setup):

> Once you have a `[tool.versioningit]` table in your `pyproject.toml` — **and once your repository has at least one tag**

If you want `versioningit` to treat a tagless repository as though the first commit has a tag, fill in the `tool.versioningit.vcs.default-tag` field in `pyproject.toml` (cf. #31), though note that this runs the risk of silently getting the wrong version if you perform a shallow checkout of your repository in GitHub Actions.

**Comment by Changaco** [comment]
Sorry I missed the relevant parts of the documentation and the previous issue.

> though note that this runs the risk of silently getting the wrong version if you perform a shallow checkout of your repository in GitHub Actions.

Have you considered adding [a check that the repository isn't shallow](https://stackoverflow.com/a/37533086) and safely falling back to a `0.0` version number by default in that case?
